### ISSUE TITLE
Unable to build from README.md instructions

### ISSUE THREAD

**Issue by rspooner-xyo** [XYOracleNetwork/api-diviner-nodejs#29]
Following your README.md instructions, I encounter a problem:

_______________
api-diviner-nodejs$> sudo npm install @xyo-network/api-diviner-nodejs -g --unsafe-perm=true
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
npm Code 1
npm Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/dignifiedquire/webcrypto-shim.git /Users/richardspooner/.npm/_cacache/tmp/git-clone-249405da
npm /Users/richardspooner/.npm/_cacache/tmp/git-clone-249405da/.git: Permission denied
_____________

The npm log file is attached.

I can write to the ~/.npm/_cache/tmp folder:
______________
api-diviner-nodejs$> ls -al ../.npm/_cacache//tmp
total 0
drwxr-xr-x  2 richardspooner  staff   64 Oct 17 18:39 
drwxr-xr-x  5 richardspooner  staff  160 Oct 17 16:11 ..

api-diviner-nodejs$> touch ../.npm/_cacache//tmp/rws.rws
api-diviner-nodejs$> ls -al ../.npm/_cacache//tmp
total 0
drwxr-xr-x  3 richardspooner  staff   96 Oct 17 18:41 .
drwxr-xr-x  5 richardspooner  staff  160 Oct 17 16:11 ..
-rw-r--r--  1 richardspooner  staff    0 Oct 17 18:41 rws.rws
api-diviner-nodejs$> rm  ../.npm/_cacache//tmp/rws.rws
______________
I can run the offending line from the command line:
______________
api-diviner-nodejs$> pwd
/Users/richardspooner/api-diviner-nodejs
api-diviner-nodejs$> /usr/bin/git clone --depth=1 -q -b master git://github.com/dignifiedquire/webcrypto-shim.git /Users/richardspooner/.npm/_cacache/tmp/git-clone-249405da
api-diviner-nodejs$> 
api-diviner-nodejs$> ls ../.npm/_cacache/tmp/git-clone-249405da/
LICENSE			bower.json		index.html		test
README.md		generate-vectors.html	package.json		webcrypto-shim.js
______________
Running again gives same failure:
______________
api-diviner-nodejs$> sudo npm install @xyo-network/api-diviner-nodejs -g --unsafe-perm=true
Password:
npm The npm log file is attached. bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2
npm  code 1
npm Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/dignifiedquire/webcrypto-shim.git /Users/richardspooner/.npm/_cacache/tmp/git-clone-064abae8
npm /Users/richardspooner/.npm/_cacache/tmp/git-clone-064abae8/.git: Permission denied
npm A complete log of this run can be found in:
npm /Users/richardspooner/.npm/_logs/2018-10-18T01_58_19_094Z-debug.log
api-diviner-nodejs$> 
______________

**Comment by arietrouw** [comment]
Docker version is fixed for the build, so please try that.  Have not verified that this is a global problem though.
