### ISSUE TITLE
[040c5d1] Problem with build/install of 0.1.11

### ISSUE THREAD

**Issue by rspooner-xyo** [XYOracleNetwork/api-diviner-nodejs#47]
Problems with User Build and Developer Build following instructions in README.md:

See attached file

[api-diviner-nodejs issue 47.docx](https://github.com/XYOracleNetwork/api-diviner-nodejs/files/2555541/api-diviner-nodejs.issue.47.docx)

**Comment by arietrouw** [comment]
Resolved in 0.1.13
